### ISSUE TITLE
Capture with settings from YML in python

### ISSUE THREAD

**Issue by EllingEye** [zivid/zivid-python#136]
Is it possible to load the exported settings from Zivid Studio in python? I've found an example showing how to do this in c++:

`const auto settingsFile = std::string(ZIVID_SAMPLE_DATA_DIR) + "/Settings/" + cameraModel + "/Settings01.yml";
 const auto settings = Zivid::Settings(settingsFile);`

But I haven't found a way to do the same with the zivid.Settings()-class in python

**Comment by trym-b** [comment]
Hi @EllingEye 

I am sorry to say but at the moment we do not have good way of reading settings from a yaml file using `zivid-python`. I have created an internal ticket for this issue.

**Comment by EllingEye** [comment]
That's okay. I'll just trow something together with pyyaml. Just wanted to check if a solution already existed. Thank you for the quick reply.

**Comment by erikschuitema** [comment]
I ran into the same issue.
This seems to do the job in 2.1.3.2.4.1:
```
import zivid
import _zivid
import zivid._settings_converter as _settings_converter
(...)
app = zivid.Application()
(...)
internal_settings = _zivid.Settings('/path/to/settings.yml')
settings = _settings_converter.to_settings(internal_settings)
```
Looking forward to the official support of this functionality :)

**Comment by eskaur** [comment]
Yes that should do the trick for now.

**One warning:** You will get inconsistent result if the yml contains values for the settings in the Zivid API that are not yet supported in the Python front-end, such as `Settings::Color::Experimental::ToneMapping` and `Settings::Experimental::Engine`. You will experience that those values will be lost in translation, and be reverted to their default values when you capture. This will be fixed by the time we provide this as official functionality, of course. If you stay away from those settings, things should be fine when using your workaround.

**Comment by eskaur** [comment]
This is now officially released to PyPI.
